-- Phase 1: Vivo Points — append-only ledger, balance view/function, category boosters.

create table erp.points_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references erp.profiles (id),
  delta int not null,
  reason erp.points_reason not null,
  order_id uuid references erp.orders (id),
  note text,
  created_by uuid references erp.profiles (id),
  created_at timestamptz not null default now(),
  constraint points_ledger_admin_adjust_needs_note
    check (reason != 'admin_adjust' or note is not null)
);

comment on table erp.points_ledger is
  'Append-only. No UPDATE/DELETE policy for any role, and the triggers below '
  'reject UPDATE/DELETE outright (defense in depth beyond RLS, since service_role '
  'bypasses RLS entirely). Correct a mistake with an offsetting row, never an edit.';

create index points_ledger_user_id_idx on erp.points_ledger (user_id);
create index points_ledger_order_id_idx on erp.points_ledger (order_id);

create or replace function erp.points_ledger_block_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'points_ledger is append-only: % is not allowed', tg_op;
end;
$$;

create trigger points_ledger_no_update
  before update on erp.points_ledger
  for each row execute function erp.points_ledger_block_mutation();

create trigger points_ledger_no_delete
  before delete on erp.points_ledger
  for each row execute function erp.points_ledger_block_mutation();

-- security_invoker: queries this view under the caller's own RLS on points_ledger,
-- so a customer only ever sees their own balance through it.
create view erp.points_balances
with (security_invoker = true) as
select
  user_id,
  sum(delta)::int as balance,
  max(created_at) as last_activity_at
from erp.points_ledger
group by user_id;

create or replace function erp.points_balance(p_user_id uuid)
returns int
language sql
stable
security invoker
set search_path = ''
as $$
  select coalesce(sum(delta), 0)::int
  from erp.points_ledger
  where user_id = p_user_id;
$$;

comment on function erp.points_balance(uuid) is
  'SECURITY INVOKER: respects the caller''s own RLS on points_ledger (no bypass).';

grant execute on function erp.points_balance(uuid) to authenticated, service_role;

create table erp.points_boosters (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references erp.categories (id),
  multiplier numeric(3, 1) not null default 2 check (multiplier > 0),
  starts_at timestamptz,
  ends_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint points_boosters_schedule_order check (starts_at is null or ends_at is null or starts_at <= ends_at)
);

create index points_boosters_category_id_idx on erp.points_boosters (category_id);

create trigger set_updated_at
  before update on erp.points_boosters
  for each row execute function erp.set_updated_at();
